version: '3.8'
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`localhost`)"
      - "traefik.http.routers.nuxt.entrypoints=web,websecure"
      - "traefik.http.routers.nuxt.tls.certresolver=le"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
