services:
  nuxt-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-dev.rule=Host(`itsinav.run`)"
      - "traefik.http.routers.nuxt-dev.entrypoints=websecure"
      - "traefik.http.routers.nuxt-dev.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    restart: unless-stopped

networks:
  web:
    external: true
