version: '3.8'

services:
  nuxt-app:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`itsinav.run`)"
      - "traefik.http.routers.nuxt.entrypoints=websecure"
      - "traefik.http.routers.nuxt.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
    networks:
      - web

networks:
  web:
    external: true
